# Generated by Django 3.2.7 on 2022-03-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='pic',
            field=models.ImageField(default='', upload_to='myimage'),
        ),
    ]
