# Generated by Django 3.2.7 on 2022-05-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_state_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(max_length=150)),
                ('Date', models.CharField(max_length=50)),
                ('Pm2', models.FloatField()),
                ('Pm10', models.FloatField()),
                ('No', models.FloatField()),
                ('No2', models.FloatField()),
                ('Nox', models.FloatField()),
                ('Nh3', models.FloatField()),
                ('Co', models.FloatField()),
                ('So2', models.FloatField()),
                ('O3', models.FloatField()),
                ('Benzene', models.FloatField()),
                ('Toluene', models.FloatField()),
                ('Xylene', models.FloatField()),
                ('Aqi', models.FloatField()),
                ('Air_quality', models.CharField(max_length=200)),
            ],
        ),
    ]
