# Generated by Django 3.2.7 on 2022-05-22 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_polution'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Polution',
            new_name='Pollution',
        ),
    ]
